### ISSUE TITLE
No source code in 1.2.0 release archives

### ISSUE THREAD

**Issue by NicoEkino** [airbnb/MvRx#308] opened 2019-10-14 14:15 UTC
Hi and thanks for this wonderful library!

It seems that there was an issue with the source code jar file published (https://repo1.maven.org/maven2/com/airbnb/android/mvrx/1.2.0/mvrx-1.2.0-sources.jar)
It contains source code for only 1 file.

Best regards,
Nicolas

**Comment by elihart** [comment] 2019-10-14 14:51
Thanks for reporting, looks like it is caused by this bug 
https://github.com/vanniktech/gradle-maven-publish-plugin/issues/47

That is fixed in a snapshot release - I can push a 1.2.1 version with the snapshot.

**Closed** 2019-10-15 14:45 UTC
