### ISSUE TITLE
Crashes using PagedList within MvRxState

### ISSUE THREAD

**Issue by VGJohn** [airbnb/MvRx#290] opened 2019-09-18 00:13 UTC
I'm trying to use the paging library with MvRx & Epoxy but I'm running into crashes caused by the PagedList inside of my MvRxState. I understand that the PagedList is mutable which goes against the immutability of the MvRxState. Is there any suggested way of using the Paging library with MvRx or should it be avoided and instead pass the PagedList to the PagedListEpoxyController through LiveData from the ViewModel? Any help would be appreciated. Thanks

**Comment by elihart** [comment] 2019-11-09 16:35
Ideally the best way to handle this is to have your ViewModel subscribe to the PageList changes, and make an immutable copy of the list into your State whenever the paged list changes.

Of course that doesn't work so well with `PagedListEpoxyController`, because you lose the ability to have the controller load pages for you, and for the Epoxy model reuse.

One alternative is to have a callback to the viewmodel to load pages as necessary, and use a normal EpoxyController. You lose the Epoxy model caching, but since you can rebuild models off the main thread it shouldn't be a huge deal.

Otherwise Epoxy would need to be updated with a change to `PagedListEpoxyController`. I think we could have a class like `PagedListEpoxyController` that was just for normal lists - it could cache models for items in the list. Alternatively you could probably make your own pretty easily - just have an EpoxyController that has a map to associate previously created models, and reuse them when you can.

**Comment by gpeal** [comment] 2020-05-18 02:48
Duplicate of #216

**Closed by gpeal** 2020-05-18 02:48 UTC
