### ISSUE TITLE
todomvrx - todo edit - state on rotation no perserved

### ISSUE THREAD

**Issue by OndrejMalek** [airbnb/MvRx#203] opened 2019-02-26 18:08 UTC
Hi, just looking into your examples and EditText does not preserve state when changed than rotated. Is it intended behavior?

**Comment by mradzinski** [comment] 2019-02-27 18:29
I guess it's the expected behavior. The text you input on the EditText isn't part of the VM state, nor its being handled in any way other than to create/edit tasks, so there's no reason for it to persist during such scenario.

You could make the user's input part of the state and have the EditText text set to this value during `invalidate` though.

**Comment by OndrejMalek** [comment] 2019-03-06 13:24
Well thx,  this does not seem like expected behavior from user perspective. To lose data on rotation.
I does not make it easier to comprehend MvRx if it is part of framework or bug.

**Comment by mradzinski** [comment] 2019-03-07 01:10
@OndrejMalek it's just a sample, not a full featured app. As such, it's intended to get you started with MvRx and not handling user input on configuration changes isn't a bug but and omittion most likely for brevity.

Anyway, you would handle user inputs almost exactly the same way as you handle other things.

**Comment by elihart** [comment] 2019-03-12 17:30
Fixed with https://github.com/airbnb/MvRx/pull/209

**Closed by elihart** 2019-03-12 17:30 UTC
